# Markdown

## Краткое руководство

# 1 level #
## 2 level
### 3 level
#### 4 level
##### 5 level
###### 6 level



In [3]:
- el 1
- el 2
- el 3

SyntaxError: invalid syntax (<ipython-input-3-4d0682c4788c>, line 1)

- el 1
- el 2
- el 3


* el 1
* el 2
    * el 2.1
* el 3

1. el 1
2. el 2
    1. el 2.1
    2. el 2.2
    

> Ragger have a higthground

***


[link](http://example.com/link "I'm ur Daddy")

![Alt text](//placehold.it/150*100 "Text")

In [4]:
import numpy as np

In [5]:
vec = np.array([1,2,3])
vec.ndim

1

In [7]:
vec.shape


(3,)

In [9]:
mat = np.array([[1,2,3], [4,5,6]])
mat.ndim

2

In [10]:
mat.itemsize

4

In [11]:
mat.dtype.name

'int32'

In [12]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [13]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [14]:
B = np.array([(1,2,3), (4,5,6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.arange( 2, 20 , 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(8).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
C = np.arange(9).reshape(3,3)
C.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [20]:
np.hstack((C, C*2))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [21]:
np.concatenate((C, C**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25],
       [ 6,  7,  8, 36, 49, 64]])

In [22]:
print A
print B

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(A)? (<ipython-input-22-62ceb1275722>, line 1)

In [23]:
print C
print B

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(C)? (<ipython-input-23-c65bb67b2418>, line 1)

In [24]:
print(C)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]]


In [25]:
 A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
B = np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
A+B

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [28]:
3*A


array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [29]:
A.dot(B)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [2]:
np.exp(A)


NameError: name 'np' is not defined

In [1]:
A.sum(axis = 1)

NameError: name 'A' is not defined

In [3]:
 A = np.arange(9).reshape(3,3)
A


NameError: name 'np' is not defined

In [4]:
import numpy as np


In [5]:
 A = np.arange(9).reshape(3,3)
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
A.sum(axis = 1)


array([ 3, 12, 21])

In [7]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[2:5]

array([2, 3, 4])

In [9]:
a[3:8:2]

array([3, 5, 7])

In [10]:
A = np.arange(81).reshape(9 , -1)

In [11]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [14]:
A[2:4,2:4]

array([[20, 21],
       [29, 30]])

In [15]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [16]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [17]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [19]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [21]:
start = time.clock()
ans = 0 
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock() - start)

c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


0.36040385100000094


c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


In [22]:
start = time.clock()
ans = sum([A_slow_list[i] *B_slow_list[i] for i in range(1000000) ])
print(time.clock() - start)

c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


0.2932759170000736


c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
start = time.clock()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.clock() - start)

0.01274900700013859


c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [24]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

0.012912488999972993


c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
c:\users\user5\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
import pandas as pd
my_series = pd.Series([5,6,7,8,9,10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [27]:
my_series.index

RangeIndex(start=0, stop=6, step=1)

In [28]:
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [29]:
my_series[4]

9

In [30]:
my_series2 = pd.Series([5,6,7,8,9,10], index = ['a','b','c','d','e','f'])
my_series2['f']

10

In [31]:
my_series2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [32]:
my_series2[['a','b','f']] = 0
my_series2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [33]:
my_series2[my_series2 > 0]

c    7
d    8
e    9
dtype: int64

In [34]:
my_series2[my_series2 > 0] *2

c    14
d    16
e    18
dtype: int64

In [35]:
my_series3 = pd.Series({'a' : 5, 'b': 6, 'c':7, 'd':8})
my_series3

a    5
b    6
c    7
d    8
dtype: int64

In [36]:
my_series3.name = 'numbers'
my_series3.index.name = 'letters'
my_series3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [37]:
my_series3.index = ['A','B','C','D']
my_series3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

In [39]:
df = pd.DataFrame({
...    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
...    'population': [17.04, 143.5, 9.5, 45.5],
...    'square': [2724902, 17125191, 207600, 603628]   
... })
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

In [40]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [41]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [42]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [43]:
df = pd.DataFrame({
...    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
...    'population': [17.04, 143.5, 9.5, 45.5],
...    'square': [2724902, 17125191, 207600, 603628]   
... }, index = ['KZ','RU','BY','UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628

In [44]:
df.index.name = 'Country Code'
df

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [45]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [47]:
df.loc[['KZ', 'RU'], 'population']

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [48]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object

In [50]:
df.loc['KZ': 'BY', :]

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600

In [52]:
df[df.population > 10][['country', 'square']]

country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628

In [53]:
df.reset_index()


Country Code     country  population    square
0           KZ  Kazakhstan       17.04   2724902
1           RU      Russia      143.50  17125191
2           BY     Belarus        9.50    207600
3           UA     Ukraine       45.50    603628

In [54]:
df['density'] = df['population'] / df['square'] * 1000000
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [55]:
df.drop(['density'], axis = 'columns')

country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628

In [56]:
df = df.rename(columns = {'Country Code': 'country_code'})
df

country  population    square    density
Country Code                                             
KZ            Kazakhstan       17.04   2724902   6.253436
RU                Russia      143.50  17125191   8.379469
BY               Belarus        9.50    207600  45.761079
UA               Ukraine       45.50    603628  75.377550

In [57]:
titanic_df = pd.read_csv('titanic.csv')
print(titanic_df.head())

FileNotFoundError: [Errno 2] File b'titanic.csv' does not exist: b'titanic.csv'